Incognito\SilextalkBase\Model\EmailMessage:
    getters:
        toAddress:
            - NotNull: ~
            - NotBlank: ~
            - Email:
                strict: true
        subject:
            - NotNull: ~
        body:
            - NotNull: ~
            - NotBlank: ~
